// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

console.log('🔍 Debug Supabase Config:');
console.log('URL:', SUPABASE_URL);
console.log('Key:', SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...');
console.log('URL type:', typeof SUPABASE_URL);
console.log('URL value:', JSON.stringify(SUPABASE_URL));

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Variáveis de ambiente do Supabase não configuradas!\n' +
    'Certifique-se de que VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY estão definidas no arquivo .env\n' +
    'Reinicie o servidor de desenvolvimento após criar/editar o arquivo .env'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});